### ISSUE TITLE
Doesn't fully support reflexive relationships

### ISSUE THREAD

**Issue by VulumeCode** [mu-semtech/mu-cl-resources#6]
In Ember it is possible to define a model "person" with a relationship
`  bestFriend: DS.belongsTo('user', { inverse: 'bestFriend' })
`
A corresponding resource cannot be defined in the domain. It's not possible to indicate that a relationship is its own inverse. 

It is possible to get close by simply defining the relationship, but then inconsistencies can arise. For instance, if Alice adds Bobs as bestfriend, in Ember Alice is also Bob's bestfriend, which is correct. But if Bob removes Alice as bestfriend, this only happens in the Ember Store but it's not persisted in the DB. Likewise, Bob could change their bestfriend, resulting in a corrupted DB. 

Note that this is not a problem if you can give different names to the relationships depending on which direction the predicate is traversed. A model "person" with relationships
```
  children: DS.hasMany('person', { inverse: 'parent' }),
  parent: DS.belongsTo('person', { inverse: 'children' })
```
Can be defined just fine. 

Some speculation: I'm not sure if this can be simply fixed without adding a new flag (like `:reflexive t`), but I'd even prefer that maybe.
Also as a shot in the dark I tried adding the relationship twice, once with `:reverse t`, but that didn't work.

**Comment by madnificent** [comment]
First of all, thanks for the issue.  We had discussed it ages ago and I honestly can't remember exactly when this issue was fixed.

To my understanding, this was an issue with internal caching and it should be fully handled by mu-cl-resources and the database being wired to the delta-notifier.  mu-cl-resources will check all changes which happen and it will clear the effective caches.

I'm closing this issue for now.  If you notice the problem still persists or if there's extra clarification we should know about, do add comments.
